sudo: false
  
install:
  - wget -q "https://github.com/gohugoio/hugo/releases/download/v0.62.2/hugo_0.62.2_Linux-64bit.tar.gz" -O "hugo.tar.gz"
  - tar -xzf hugo.tar.gz

script:
  - ./hugo

deploy:
  provider: pages
  repo: rsrini7/rsrini7.github.io
  target-branch: master
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master