baseurl = "https://rsrini7.github.io/"
languageCode = "en-US"
title = "Srini"
# Enable comments by entering your Disqus shortname
disqusShortname = "rsrini7-1"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"
pygmentsCodeFences = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "rsrini7"
  avatarUrl = ""
  author = "Srini"
  description = "A site for me"
  about = """
        <h3>Srini is a passionate developer, who specializes in enterprise applications and systems.</h3>
        <h3>He is also an active contributor and a strong advocate for Open source software.</h3>
     """

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "rsrini7"
  Email         = "7rsrini@gmail.com"
  Twitter       = "rsrini_7"
  LinkedIn      = "rsrini7"
  Stackoverflow = "users/11617413/srini-r"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]  
  name = "talks"
  identifier = "talks"
  weight = 200
  url = "/talks/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 300
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 400
  url = "https://github.com/rsrini7/resume/raw/master/Srinivasan_Ragothaman_Resume.pdf"